Change date format on parent components props with default value
InfectoOne/vue-ganttastic pull request #16
Opened 2021-11-09 14:41 UTC by qqMelon

This change can be used to dynamize the date formats by sending directly in props in the component GantChart `:day-format="value"`

This props has a default value and is not required, no change is required if the lib is update.

By default the value is: `"dddd, DD. MMMM" string` <-- recover from the data

cordially.

2021-11-09 14:49 UTC, WegPast commented
This is a must ! It need to be pulled !

2021-12-07 17:39 UTC, InfectoOne requested changes
It is a nice feature, but in this commit, the new `dayFormat `prop was merely defined. It is not being used anywhere yet.

2022-01-12 20:32 UTC, InfectoOne commented
By the way: if you are using Vue 3, check out the latest version of Vue-Ganttastic. There is a new prop called `date-format` that determines the format of all relevant dates (chart stat, chart end and bar starts and ends). For formatting the *displayed* date in the time axis, there are slots available for that.

2022-05-10 06:31 UTC, InfectoOne commented
Closed due to inactivity.

2022-05-10 06:31 UTC, closed without merging

2024-05-02 21:58 UTC, y377 commented
> By the way: if you are using Vue 3, check out the latest version of Vue-Ganttastic. There is a new prop called `date-format` that determines the format of all relevant dates (chart stat, chart end and bar starts and ends). For formatting the _displayed_ date in the time axis, there are slots available for that.

What slot should I use to format it as `YYYY-MM-DD`? I can't use this one,
```
<g-gantt-chart chart-start="2024-01-01" chart-end="2025-03-22" precision="day" bar-start="myBeginDate"
bar-end="myEndDate" date-format="YYYY-MM-DD">
```
Any reply is greatly appreciated!